# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCred < Formula
  desc "kubectl-cred is a kubernetes plugin to which switch to contexts using an interactive CLI."
  homepage ""
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.0.9/kubectl-cred_v0.0.9_Darwin_x86_64.tar.gz"
    sha256 "868b552f7412d0fb26eb8c069fb5d32361466342855ac59abaea7bb89eb1d845"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.0.9/kubectl-cred_v0.0.9_Linux_x86_64.tar.gz"
    sha256 "f1066bf14630cce2c621002b1bae5030cf251c14c1c8601801bda5e760ff55af"
  end

  def install
    bin.install "kubectl-cred"
  end
end
