# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlCred < Formula
  desc "kubectl-cred is a kubernetes plugin to which switch to contexts using an interactive CLI."
  homepage ""
  version "0.2.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.2.6/kubectl-cred_v0.2.6_Darwin_arm64.tar.gz"
      sha256 "a46db6760f0b14d9ce4c22da232bcbf3da2baa22f9c9f97d43483389d3f8ee52"

      def install
        bin.install "kubectl-cred"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.2.6/kubectl-cred_v0.2.6_Darwin_x86_64.tar.gz"
      sha256 "248146599943a836e433c387827c724875ca2c2e1ab55839a03bf9da4846f9a0"

      def install
        bin.install "kubectl-cred"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.2.6/kubectl-cred_v0.2.6_Linux_arm64.tar.gz"
      sha256 "7eb098c5155d9ea0b49cb677d0bda14ed0a7f5692730302986a0c551076ad698"

      def install
        bin.install "kubectl-cred"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gjbae1212/kubectl-cred/releases/download/v0.2.6/kubectl-cred_v0.2.6_Linux_x86_64.tar.gz"
      sha256 "a3840f175c47bca5c00df5ecac15c42af43e07b859e2d73ec89cffe5ecc04a9d"

      def install
        bin.install "kubectl-cred"
      end
    end
  end
end
